site_name: SwarmNXT
repo_url: https://github.com/lis-epfl/swarm-nxt
repo_name: GitHub
# edit_uri will be determined automatically by RTD based on the version being built
# For main branch: edit/main/docs/
# For devel branch: edit/devel/docs/
# For tags: edit/{tag}/docs/
nav: 
  - Home: index.md
  - Infrastructure Setup: infra-setup.md
  - Drone Build Instructions: drone-setup.md
  - Remote Control Setup: remote-control-setup.md
  - Flying: flying.md
  - Common Software Tasks: software-common-tasks.md
  - Manual Setup Instructions: manual-setup.md
  - Read the Docs Setup: readthedocs-setup.md
  - Appendix: appendix.md
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - asciinema-player
      
extra_javascript:
  - js/mathjax.js
  - js/copy-button.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css
