site_name: Omni NXT
nav: 
  - Home: index.md
  - Infrastructure Setup: infra-setup.md
  - Drone Build Instructions: drone-setup.md
  - Flying: flying.md
  - Common Software Tasks: software-common-tasks.md
  - Manual Setup Instructions: manual-setup.md
  - Appendix: appendix.md
theme: readthedocs
markdown_extensions:
  - admonition
