# Multi-drone logging configuration for SwarmNXT
# This configuration supports synchronized logging across multiple drones in a swarm

multi_drone_logger:
  ros__parameters:
    # Drone namespaces to monitor
    drone_namespaces: ["nxt1", "nxt2", "nxt3", "nxt4"]
    
    # Topics common to all drones
    common_topics:
      - "/mavros/local_position/pose"
      - "/mavros/state"
      - "/mavros/setpoint_position/local"
      - "/latency_checker/heartbeat"
      - "/drone_planner/trajectory"
      - "/swarmnxt_controller/command"
    
    # Topics specific to each drone (will be prefixed with namespace)
    drone_specific_topics:
      - "/mavros/imu/data"
      - "/mavros/global_position/global"
      - "/mavros/battery"
      - "/safety_checker/violations"
      - "/bounds_checker/status"
    
    # Synchronization settings
    sync_logging: true
    sync_tolerance_ms: 10  # Maximum time difference for synchronized logging
    
    # Output configuration
    output_directory: "/shared/logs/swarm"
    bag_name_prefix: "swarm_mission"
    separate_bags_per_drone: false  # Single bag file vs one per drone
    
    # Storage settings
    max_bag_size_mb: 1000
    compression: "zstd"
    split_duration: 120  # seconds (2 minutes)
    
    # Performance settings
    buffer_size: 1000000  # bytes
    max_files_open: 20