# Debug logging configuration for SwarmNXT
# This configuration captures detailed data for debugging flight issues

debug_logger:
  ros__parameters:
    # High-frequency topics for detailed analysis
    high_frequency_topics:
      - "/mavros/imu/data"                    # 100+ Hz IMU data
      - "/mavros/local_position/velocity_local" # Velocity estimates
      - "/mavros/setpoint_raw/local"          # Raw setpoint commands
      - "/mavros/rc/in"                       # Remote control inputs
    
    # Standard frequency topics
    standard_topics:
      - "/mavros/local_position/pose"
      - "/mavros/state"
      - "/mavros/extended_state"
      - "/mavros/actuator_control"
      - "/mavros/manual_control/control"
    
    # Low frequency topics
    low_frequency_topics:
      - "/mavros/battery"
      - "/mavros/sys_status"
      - "/mavros/param/param_value"
    
    # System and diagnostic topics
    diagnostic_topics:
      - "/safety_checker/violations"
      - "/bounds_checker/status"
      - "/latency_checker/heartbeat"
      - "/rosout"                             # ROS log messages
    
    # QoS profiles for different topic types
    qos_profiles:
      high_frequency:
        depth: 1000
        reliability: "best_effort"
        history: "keep_last"
      
      standard:
        depth: 10
        reliability: "reliable"
        history: "keep_last"
      
      diagnostic:
        depth: 100
        reliability: "reliable"
        history: "keep_all"
    
    # Debug-specific settings
    include_tf_static: true
    include_tf: true
    include_system_topics: true
    log_level: "DEBUG"
    
    # Output configuration
    output_directory: "/home/lis/debug_logs"
    bag_name_prefix: "debug_session"
    timestamp_in_filename: true
    
    # Storage settings optimized for debug data
    max_bag_duration: 60   # seconds (1 minute per file)
    compression: "lz4"     # Fast compression for real-time debugging
    max_bag_size_mb: 2000  # Larger files for debug data