---
- name: Pre-Setup
  hosts: drones
  remote_user: lis
  become: yes # runs everything with sudo 

  tasks: 
  # TODO check if kernel exists, if it does not then patch and build. 
  # build reqs: gcc-aarch64-linux-gnu bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl perl-base rsync tar xz-utils
  # regardless, send the files over. 

  - name: Perform a safe upgrade # installs new packages if needed
    ansible.builtin.apt:
      upgrade: "safe"
  - name: Ensure apt packages are installed
    ansible.builtin.apt: 
      name: 
        - python3-pip 
        - htop 
        - sysstat
      state: latest
  - name: Jetson Stats
    ansible.builtin.pip:
      name: 
        - jetson-stats
  - name: Ensure Jetson clocks service
    ansible.builtin.template: 
      src: templates/jetson_clocks.j2
      dest: /etc/systemd/system/jetson_clocks.service

  - name: Start and enable clocks service
    ansible.builtin.systemd:
      name: jetson_clocks
      state: started
      enabled: true
      daemon_reload: true


  - name: Set max power mode 
    ansible.builtin.command: nvpmodel -m 0 --force
    async: 1
    poll: 0 # skip to next task 
    ignore_errors: true # TODO: make this less fragile
  
  - name: Wait for the system to come back up
    ansible.builtin.wait_for_connection:
      # delay: 10
      timeout: 360 
  
  - name: Ensure power save disable service
    ansible.builtin.template: 
      src: templates/disable-wifi-powersave.j2
      dest: /etc/systemd/system/disable-wifi-powersave.service
  
  - name: Start and enable the power save inhibition service
    ansible.builtin.systemd:
      name: disable-wifi-powersave
      state: started
      enabled: true
      daemon_reload: true

  - name: "Setup VNC"
    block: 
      - name: Enable Automatic Login
        ansible.builtin.lineinfile: 
          path: /etc/gdm3/custom.conf
          regexp: 'AutomaticLoginEnable'
          line: 'AutomaticLoginEnable=true'
      - name: Set automatic login user
        ansible.builtin.lineinfile: 
          path: /etc/gdm3/custom.conf
          regexp: 'AutomaticLogin'
          line: 'AutomaticLogin=lis'
      - name: Install xorg dummy
        ansible.builtin.apt: 
          name: 
            - xserver-xorg-video-dummy
            - vino
      - name: Add vino to graphical session wants
        ansible.builtin.file: 
          src: /usr/lib/systemd/user/vino-server.service
          path: /usr/lib/systemd/user/graphical-session.target.wants/vino-server.service
          state: "link"
      - name: "Set gsettings"
        become: false
        block:
          # TODO: for some reason the community dcom modifier doesn't work. this is a hack to keep going. 
          - name: "Disable prompt requirement"
            ansible.builtin.command: gsettings set org.gnome.Vino prompt-enabled false 
          - name: "Disable encryption"
            ansible.builtin.command: gsettings set org.gnome.Vino require-encryption false
          - name: "Set VNC as auth method"
            ansible.builtin.command: gsettings set org.gnome.Vino authentication-methods \"[\'vnc\']\"

            # shell to allow for this evaluation 
          - name: "Set password"
            ansible.builtin.shell: gsettings set org.gnome.Vino vnc-password $(echo -n 'thepassword'|base64)  # TODO: actual password? 

      - name: "xorg configuration"
        ansible.builtin.blockinfile:
          path: /etc/X11/xorg.conf
          append_newline: true
          prepend_newline: true
          block: |
            Section "Device"
            Identifier "Dummy0"
            Driver "dummy"
            VideoRam 16384
            EndSection

            Section "Monitor"
            Identifier "Monitor0"
            HorizSync 5.0-1000.0
            VertRefresh 5.0-200.0
            Modeline "1280x800" 24.15 1280 1312 1400 1432 800 819 822 841
            # Modeline "1920x1080_24.00" 173.00 1920 2048 2248 2576 1080 1083 1088 1120
            EndSection

            Section "Screen"
            Identifier "Screen0"
            Monitor "Monitor0"
            Device "Dummy0"
            DefaultDepth 24
            SubSection "Display"
            Depth 24
            Virtual 1280 800
            # Virtual 1920 1080
            EndSubSection
            EndSection
  - name: Setup ROS
    block: 
      - name: Ensure universe is present
        ansible.builtin.lineinfile:
          path: /etc/apt/sources.list
          line: "deb http://ports.ubuntu.com/ubuntu-ports/ jammy universe"
      - name: Ensure universe updates is present
        ansible.builtin.lineinfile:
          path: /etc/apt/sources.list
          line: "deb http://ports.ubuntu.com/ubuntu-ports/ jammy-updates universe"
      - name: Ensure software-properties-common is installed
        ansible.builtin.apt: 
          name: software-properties-common
        

        