---
- name: Pre-Setup
  hosts: local_drone
  remote_user: lis
  become: yes # runs everything with sudo 
  vars_prompt: 
    - name: hostname
      prompt: "Enter the hostname the device should have (it should be unique)"
      confirm: true
      private: false

  tasks:
    - name: "Common Components"
      ansible.builtin.include_tasks: "tasks/setup-common.yml"
    - name: Set hostname
      block:
      - name: "Set hostname in system"
        ansible.builtin.hostname: 
            name: "{{ hostname }}"
      - name: Modify /etc/hosts
        ansible.builtin.replace:
          path: /etc/hosts
          regexp: '(127\.0\.1\.1\s+).+'
          replace: \1{{ hostname }}


