# you can change enable_cameras / enable_depth in group_vars/all per drone
# by appending them at the end: nxt1.local enable_depth=true
# (enable_depth turns on cameras + depth estimation; enable_cameras turns on cameras only)
[drones]
; nxt1.local
nxt2.local enable_depth=true
nxt3.local enable_depth=true
; nxt4.local
; nxt5.local
nxt6.local enable_depth=true
; nxt7.local
; nxt8.local
; nxt9.local
nxt10.local enable_depth=true
; nxt11.local

[drones:vars]
ansible_become_password=orin

[local_drone]
192.168.55.1 

[local]
127.0.0.1

localhost ansible_connection=local
